"""Deterministic synthetic corpus generator for Phase 2 tokenizer training.

This is NOT the Phase 4 model-training corpus. Its only job is to teach a
BPE tokenizer realistic mathematical-language *segmentation* — enough
linguistic and symbolic diversity to produce sensible vocabulary pieces,
not a capability benchmark. See docs/RESEARCH_NOTES.md and
reports/PHASE2_REPORT.md for the corpus philosophy.

Every category generator is a pure function of an integer seed: same seed
and category always produce byte-identical output, so the corpus (and the
tokenizer trained from it) is reconstructible from this file alone plus the
seed recorded in config/tokenizer.yaml. Nothing here reads the clock, the
network, or global ``random`` state.
"""

from __future__ import annotations

import random
from collections.abc import Iterator
from dataclasses import dataclass

MASTER_SEED = 20260201

# Category proportions of the tokenizer-training corpus. Chosen to reflect
# Juniper Math 1's role as a math *specialist* that still understands the
# ordinary English surrounding math problems (Phase 2 spec Sec. 10, 13):
# natural-language word problems and explanations get the largest shares
# (that is most of what the model reads at inference time), numeric/symbolic
# categories get enough coverage to teach notation without letting numeric
# sludge dominate (Sec. 12), and tool syntax / errors get a small but
# guaranteed-nonzero share since Phase 3 depends on these strings tokenizing
# cleanly. Must sum to 1.0 exactly (checked in tests/test_tokenizer_corpus.py).
CATEGORY_PROPORTIONS: dict[str, float] = {
    "natural_language_math_problems": 0.22,
    "arithmetic": 0.12,
    "algebra": 0.10,
    "percentages": 0.05,
    "ratios_proportions": 0.05,
    "units": 0.08,
    "financial_math": 0.08,
    "scientific_notation": 0.04,
    "explanations": 0.10,
    "tool_syntax": 0.06,
    "errors": 0.03,
    "general_english": 0.07,
}

assert abs(sum(CATEGORY_PROPORTIONS.values()) - 1.0) < 1e-9

DEFAULT_TOTAL_LINES = 200_000

_UNITS = [
    "mm",
    "cm",
    "m",
    "km",
    "in",
    "ft",
    "yd",
    "mi",
    "mg",
    "g",
    "kg",
    "oz",
    "lb",
    "mL",
    "L",
    "°C",
    "°F",
    "K",
    "seconds",
    "minutes",
    "hours",
]

_MATH_UNICODE = [
    "×",
    "÷",
    "−",
    "±",
    "≤",
    "≥",
    "≠",
    "≈",
    "√",
    "π",
    "∞",
    "°",
    "²",
    "³",
    "∑",
    "∫",
    "α",
    "β",
    "θ",
    "Δ",
]

_VERBS = ["Calculate", "Find", "Solve", "Estimate", "Convert", "Determine", "Compute", "Simplify"]

_NOUNS = [
    "apples",
    "marbles",
    "books",
    "students",
    "miles",
    "dollars",
    "boxes",
    "cars",
    "cookies",
    "tickets",
    "pages",
    "bottles",
    "coins",
    "trees",
    "chairs",
    "bricks",
    "gallons",
    "liters",
    "workers",
    "days",
]

_NAMES = ["Maria", "James", "Priya", "Wei", "Fatima", "Liam", "Aisha", "Noah", "Sofia", "Kenji"]

_GENERAL_WORDS = [
    # function words / connectives
    "the",
    "a",
    "an",
    "and",
    "or",
    "but",
    "if",
    "then",
    "because",
    "since",
    "although",
    "however",
    "therefore",
    "meanwhile",
    "otherwise",
    "nevertheless",
    "furthermore",
    "instead",
    "besides",
    "moreover",
    "unless",
    "until",
    "while",
    "whereas",
    "though",
    "when",
    "where",
    "why",
    "how",
    "who",
    "which",
    "what",
    "whose",
    "whom",
    # instructions / verbs
    "understand",
    "explain",
    "consider",
    "compare",
    "describe",
    "imagine",
    "remember",
    "notice",
    "estimate",
    "measure",
    "count",
    "divide",
    "multiply",
    "subtract",
    "add",
    "combine",
    "separate",
    "arrange",
    "organize",
    "collect",
    "distribute",
    "share",
    "exchange",
    "trade",
    "build",
    "design",
    "plan",
    "prepare",
    "review",
    "check",
    "verify",
    "confirm",
    "decide",
    "choose",
    "select",
    "identify",
    "locate",
    "discover",
    "observe",
    "record",
    "report",
    "read",
    "write",
    "speak",
    "listen",
    "travel",
    "arrive",
    "depart",
    "return",
    "wait",
    "begin",
    "continue",
    "finish",
    "complete",
    "start",
    "stop",
    "pause",
    "resume",
    # relationships / comparisons
    "more",
    "less",
    "fewer",
    "greater",
    "smaller",
    "larger",
    "equal",
    "unequal",
    "similar",
    "different",
    "same",
    "opposite",
    "related",
    "unrelated",
    "proportional",
    "consistent",
    "than",
    "compared",
    "relative",
    "approximately",
    "roughly",
    "exactly",
    "precisely",
    "at least",
    "at most",
    "between",
    "among",
    "within",
    "beyond",
    "above",
    "below",
    # quantities / ambiguity
    "some",
    "many",
    "few",
    "several",
    "most",
    "all",
    "none",
    "any",
    "every",
    "each",
    "enough",
    "insufficient",
    "sufficient",
    "unclear",
    "ambiguous",
    "uncertain",
    "unknown",
    "possible",
    "impossible",
    "likely",
    "unlikely",
    "reasonable",
    "unreasonable",
    # objects
    "table",
    "chair",
    "window",
    "garden",
    "kitchen",
    "river",
    "mountain",
    "city",
    "village",
    "bridge",
    "road",
    "vehicle",
    "bicycle",
    "airplane",
    "train",
    "boat",
    "container",
    "package",
    "shelf",
    "wall",
    "floor",
    "ceiling",
    "door",
    "gate",
    "fence",
    "field",
    "farm",
    "factory",
    "office",
    "store",
    "market",
    "warehouse",
    "library",
    "museum",
    # people / roles
    "friend",
    "teacher",
    "doctor",
    "engineer",
    "musician",
    "traveler",
    "reader",
    "writer",
    "student",
    "parent",
    "child",
    "neighbor",
    "customer",
    "manager",
    "scientist",
    "farmer",
    "driver",
    "artist",
    "athlete",
    "volunteer",
    "employee",
    "employer",
    "colleague",
    # time
    "morning",
    "afternoon",
    "evening",
    "night",
    "weekend",
    "holiday",
    "meeting",
    "journey",
    "story",
    "week",
    "month",
    "year",
    "decade",
    "century",
    "moment",
    "period",
    "season",
    "schedule",
    "calendar",
    "deadline",
    "duration",
    "interval",
    "sequence",
    "frequency",
    # money
    "budget",
    "expense",
    "income",
    "savings",
    "invoice",
    "receipt",
    "wage",
    "salary",
    "cost",
    "price",
    "value",
    "worth",
    "payment",
    "purchase",
    "sale",
    "transaction",
    # descriptive
    "large",
    "small",
    "bright",
    "quiet",
    "distant",
    "familiar",
    "unexpected",
    "reliable",
    "narrow",
    "wide",
    "deep",
    "shallow",
    "heavy",
    "light",
    "strong",
    "weak",
    "smooth",
    "rough",
    "warm",
    "cold",
    "fresh",
    "stale",
    "clean",
    "dirty",
    "empty",
    "full",
    "simple",
    "complex",
    "clear",
    "vague",
    "urgent",
    "gradual",
    "sudden",
    "steady",
    # additional common vocabulary (breadth over the general-English surface, Sec. 10)
    "ability",
    "absence",
    "accept",
    "access",
    "account",
    "achieve",
    "acquire",
    "action",
    "activity",
    "actual",
    "address",
    "adjust",
    "advance",
    "advantage",
    "advice",
    "affect",
    "afford",
    "agency",
    "agree",
    "agreement",
    "allow",
    "almost",
    "alone",
    "already",
    "although",
    "always",
    "amount",
    "analysis",
    "ancient",
    "animal",
    "announce",
    "annual",
    "answer",
    "anxious",
    "appear",
    "apply",
    "approach",
    "appropriate",
    "approve",
    "area",
    "argue",
    "arrange",
    "arrival",
    "aspect",
    "assist",
    "assume",
    "attach",
    "attempt",
    "attend",
    "attention",
    "attitude",
    "attract",
    "author",
    "authority",
    "available",
    "aware",
    "background",
    "balance",
    "barely",
    "basic",
    "battle",
    "beauty",
    "become",
    "behave",
    "behavior",
    "belief",
    "believe",
    "belong",
    "benefit",
    "beside",
    "beyond",
    "birth",
    "border",
    "boundary",
    "brief",
    "bring",
    "broad",
    "budget",
    "burden",
    "capable",
    "capacity",
    "capital",
    "career",
    "careful",
    "carry",
    "category",
    "cause",
    "central",
    "century",
    "certain",
    "chain",
    "chance",
    "change",
    "channel",
    "chapter",
    "character",
    "charge",
    "chart",
    "circle",
    "circumstance",
    "citizen",
    "civil",
    "claim",
    "class",
    "classic",
    "climate",
    "close",
    "closely",
    "coach",
    "collect",
    "college",
    "combine",
    "comfort",
    "command",
    "comment",
    "commit",
    "common",
    "community",
    "company",
    "compare",
    "compete",
    "complete",
    "concept",
    "concern",
    "conclude",
    "condition",
    "conduct",
    "conference",
    "confidence",
    "conflict",
    "confront",
    "connect",
    "consequence",
    "conserve",
    "consider",
    "consist",
    "constant",
    "construct",
    "consult",
    "consume",
    "contact",
    "contain",
    "content",
    "context",
    "continue",
    "contract",
    "contrast",
    "contribute",
    "control",
    "convert",
    "core",
    "correct",
    "council",
    "counter",
    "country",
    "county",
    "couple",
    "courage",
    "course",
    "cover",
    "create",
    "credit",
    "crisis",
    "criteria",
    "critical",
    "crowd",
    "crucial",
    "culture",
    "current",
    "curve",
    "custom",
    "damage",
    "dangerous",
    "data",
    "deal",
    "debate",
    "debt",
    "decade",
    "deep",
    "defeat",
    "defend",
    "define",
    "degree",
    "delay",
    "deliver",
    "demand",
    "democracy",
    "demonstrate",
    "deny",
    "depend",
    "depth",
    "derive",
    "describe",
    "design",
    "desire",
    "detail",
    "detect",
    "determine",
    "develop",
    "device",
    "devote",
    "difference",
    "direct",
    "director",
    "disagree",
    "disappear",
    "discipline",
    "discover",
    "discuss",
    "disease",
    "display",
    "distance",
    "distinct",
    "distribute",
    "district",
    "diverse",
    "divide",
    "document",
    "domestic",
    "dominant",
    "double",
    "doubt",
    "draft",
    "dramatic",
    "dream",
    "drive",
    "dynamic",
    "eager",
    "earlier",
    "early",
    "economic",
    "economy",
    "edge",
    "editor",
    "educate",
    "effect",
    "efficient",
    "effort",
    "either",
    "election",
    "element",
    "eliminate",
    "emerge",
    "emotion",
    "emphasis",
    "employ",
    "empty",
    "enable",
    "encourage",
    "energy",
    "enforce",
    "engage",
    "enhance",
    "enjoy",
    "enormous",
    "ensure",
    "enter",
    "entire",
    "entrance",
    "environment",
    "episode",
    "equal",
    "equip",
    "equivalent",
    "error",
    "escape",
    "essay",
    "essential",
    "establish",
    "estate",
    "eventually",
    "evidence",
    "evolve",
    "exact",
    "examine",
    "example",
    "exceed",
    "excellent",
    "except",
    "exchange",
    "excite",
    "exclude",
    "exercise",
    "exhibit",
    "exist",
    "expand",
    "expect",
    "expense",
    "experience",
    "expert",
    "explain",
    "explore",
    "expose",
    "express",
    "extend",
    "extent",
    "external",
    "extra",
    "extreme",
    "facility",
    "factor",
    "faculty",
    "failure",
    "faith",
    "familiar",
    "fashion",
    "fault",
    "favor",
    "feature",
    "federal",
    "figure",
    "final",
    "finance",
    "finding",
    "firm",
    "flexible",
    "float",
    "flow",
    "focus",
    "follow",
    "forever",
    "formal",
    "format",
    "former",
    "formula",
    "fortune",
    "forward",
    "foundation",
    "frame",
    "framework",
    "frequent",
    "frequently",
    "front",
    "function",
    "fundamental",
    "further",
    "future",
    "gather",
    "gender",
    "general",
    "generate",
    "generation",
    "genuine",
    "global",
    "goal",
    "govern",
    "grade",
    "grant",
    "grasp",
    "grateful",
    "grocery",
    "ground",
    "growth",
    "guarantee",
    "guard",
    "guess",
    "guide",
    "habit",
    "handle",
    "harvest",
    "hazard",
    "header",
    "heritage",
    "hesitate",
    "hidden",
    "highlight",
    "hint",
    "honest",
    "horizon",
    "household",
    "human",
    "identity",
    "ignore",
    "illegal",
    "illustrate",
    "image",
    "immediate",
    "impact",
    "implement",
    "imply",
    "import",
    "important",
    "impose",
    "improve",
    "incentive",
    "incident",
    "include",
    "income",
    "increase",
    "indeed",
    "independent",
    "indicate",
    "individual",
    "industry",
    "influence",
    "inform",
    "initial",
    "initiative",
    "injury",
    "inner",
    "innovation",
    "input",
    "inquiry",
    "insight",
    "insist",
    "inspect",
    "install",
    "instance",
    "instant",
    "instead",
    "institute",
    "instruct",
    "instrument",
    "insurance",
    "integrate",
    "intelligence",
    "intend",
    "intense",
    "interact",
    "interest",
    "interfere",
    "internal",
    "interpret",
    "interrupt",
    "interval",
    "intervene",
    "interview",
    "introduce",
    "invest",
    "investigate",
    "invite",
    "involve",
    "isolate",
    "issue",
    "item",
    "journal",
    "judge",
    "justice",
    "justify",
    "keen",
    "knowledge",
    "labor",
    "landscape",
    "language",
    "layer",
    "leadership",
    "league",
    "learn",
    "legacy",
    "legal",
    "legislation",
    "leisure",
    "level",
    "liberty",
    "license",
    "limit",
    "link",
    "literary",
    "literature",
    "local",
    "logic",
    "loyal",
    "maintain",
    "major",
    "manage",
    "manner",
    "manufacture",
    "margin",
    "material",
    "matter",
    "maximum",
    "mechanism",
    "media",
    "medical",
    "member",
    "memory",
    "mental",
    "mention",
    "merge",
    "method",
    "minimum",
    "minor",
    "minority",
    "mission",
    "mixture",
    "mobile",
    "modest",
    "modify",
    "monitor",
    "moral",
    "motion",
    "motivate",
    "movement",
    "mutual",
    "narrative",
    "nation",
    "native",
    "natural",
    "nature",
    "nearby",
    "necessary",
    "negative",
    "negotiate",
    "network",
    "neutral",
    "normal",
    "notable",
    "notion",
    "nutrition",
    "object",
    "objective",
    "obligation",
    "observation",
    "obtain",
    "obvious",
    "occasion",
    "occupy",
    "occur",
    "offer",
    "official",
    "operate",
    "operation",
    "opinion",
    "opponent",
    "opportunity",
    "oppose",
    "option",
    "orange",
    "orbit",
    "order",
    "ordinary",
    "organize",
    "orient",
    "origin",
    "original",
    "outcome",
    "outline",
    "output",
    "overall",
    "overcome",
    "overlap",
    "oversee",
    "owner",
    "pace",
    "panel",
    "parallel",
    "parameter",
    "partial",
    "participate",
    "particular",
    "partner",
    "passage",
    "passion",
    "pattern",
    "pause",
    "perceive",
    "percent",
    "perform",
    "perhaps",
    "permanent",
    "permit",
    "perspective",
    "phase",
    "phenomenon",
    "philosophy",
    "physical",
    "pioneer",
    "portion",
    "position",
    "positive",
    "possess",
    "potential",
    "practical",
    "practice",
    "precise",
    "predict",
    "preference",
    "prepare",
    "presence",
    "present",
    "preserve",
    "pressure",
    "prevent",
    "previous",
    "primary",
    "principle",
    "priority",
    "private",
    "procedure",
    "proceed",
    "process",
    "produce",
    "product",
    "profession",
    "profile",
    "profit",
    "program",
    "progress",
    "project",
    "prominent",
    "promote",
    "prompt",
    "proper",
    "property",
    "proportion",
    "proposal",
    "propose",
    "prospect",
    "protect",
    "protest",
    "prove",
    "provide",
    "province",
    "provision",
    "public",
    "publish",
    "purchase",
    "purpose",
    "pursue",
    "qualify",
    "quality",
    "quantity",
    "quarter",
    "query",
    "quote",
    "random",
    "range",
    "rapid",
    "rare",
    "rather",
    "ratio",
    "reach",
    "react",
    "reader",
    "readily",
    "realistic",
    "reality",
    "realize",
    "reason",
    "recall",
    "receive",
    "recent",
    "recognize",
    "recommend",
    "reduce",
    "refer",
    "reflect",
    "reform",
    "refuse",
    "regard",
    "region",
    "register",
    "regular",
    "regulate",
    "reinforce",
    "reject",
    "relate",
    "release",
    "relevant",
    "reliable",
    "relief",
    "rely",
    "remain",
    "remark",
    "remind",
    "remote",
    "remove",
    "render",
    "renew",
    "repair",
    "repeat",
    "replace",
    "reply",
    "represent",
    "require",
    "research",
    "reserve",
    "resident",
    "resist",
    "resolve",
    "resort",
    "resource",
    "respect",
    "respond",
    "response",
    "restore",
    "restrict",
    "result",
    "resume",
    "retain",
    "reveal",
    "revenue",
    "reverse",
    "review",
    "revise",
    "reward",
    "rigid",
    "rise",
    "risk",
    "role",
    "route",
    "routine",
    "rural",
    "sample",
    "satisfy",
    "scale",
    "scenario",
    "scheme",
    "scope",
    "section",
    "sector",
    "secure",
    "seek",
    "segment",
    "senior",
    "sense",
    "sensitive",
    "separate",
    "sequence",
    "series",
    "session",
    "setting",
    "settle",
    "shape",
    "shift",
    "shortly",
    "shrink",
    "signal",
    "significant",
    "similar",
    "simultaneous",
    "site",
    "situation",
    "skill",
    "slight",
    "social",
    "solid",
    "solution",
    "somewhat",
    "source",
    "specific",
    "spectrum",
    "sphere",
    "spread",
    "stable",
    "stage",
    "standard",
    "state",
    "statement",
    "status",
    "steady",
    "stimulate",
    "straight",
    "strategy",
    "strength",
    "stress",
    "strict",
    "structure",
    "struggle",
    "submit",
    "subsequent",
    "substance",
    "substantial",
    "succeed",
    "success",
    "sufficient",
    "suggest",
    "suitable",
    "summary",
    "supply",
    "support",
    "suppose",
    "surface",
    "surround",
    "survey",
    "survive",
    "suspect",
    "sustain",
    "symbol",
    "system",
    "target",
    "task",
    "technical",
    "technique",
    "technology",
    "temporary",
    "tendency",
    "tension",
    "term",
    "territory",
    "theme",
    "theory",
    "therefore",
    "thorough",
    "thought",
    "threat",
    "tolerate",
    "topic",
    "tough",
    "toward",
    "trace",
    "track",
    "tradition",
    "transfer",
    "transform",
    "transition",
    "transport",
    "treat",
    "tremendous",
    "trend",
    "trial",
    "trust",
    "typical",
    "ultimate",
    "undergo",
    "undertake",
    "uniform",
    "unique",
    "unit",
    "universal",
    "upcoming",
    "update",
    "upgrade",
    "urban",
    "usage",
    "utilize",
    "vacant",
    "valid",
    "variable",
    "variation",
    "variety",
    "various",
    "vast",
    "vehicle",
    "version",
    "vessel",
    "victim",
    "violate",
    "virtual",
    "vision",
    "visual",
    "vital",
    "volume",
    "voluntary",
    "vulnerable",
    "warn",
    "wealth",
    "welfare",
    "whatever",
    "whenever",
    "wherever",
    "whether",
    "widespread",
    "willing",
    "wisdom",
    "withdraw",
    "witness",
    "worry",
    "worth",
    "yield",
]

_EXPLANATIONS = [
    "First divide both sides by {n}.",
    "The denominator cannot be zero.",
    "This result is undefined.",
    "The values are insufficient to determine a unique answer.",
    "Subtract {n} from both sides to isolate the variable.",
    "Multiply both sides by {n} to clear the fraction.",
    "Round the answer to two decimal places.",
    "Check the units before comparing the two quantities.",
    "The negative sign applies to the entire expression.",
    "Simplify the fraction before converting to a percentage.",
    "This equation has no real solution.",
    "Substitute the known value back into the original equation.",
    "The remainder must be smaller than the divisor.",
    "Express the final answer as a reduced fraction.",
    "Convert the mixed number to an improper fraction first.",
]

_ERRORS = [
    "division by zero",
    "invalid operation",
    "unsupported unit",
    "malformed expression",
    "insufficient information",
    "tool unavailable",
    "unknown variable",
    "overflow in computation",
    "ambiguous rounding mode",
    "mismatched units in expression",
]

_TOOL_TOKENS = ["<tool_call>", "<tool_result>", "<final>", "<unsupported>", "<error>"]


def _rng_for(category: str, seed: int) -> random.Random:
    """Independent, deterministic RNG per category so categories never interact."""
    return random.Random(f"{seed}:{category}")


def _rand_int(rng: random.Random, digits_max: int = 6, allow_negative: bool = True) -> int:
    n = rng.randint(0, 10 ** rng.randint(1, digits_max) - 1)
    if allow_negative and rng.random() < 0.15:
        n = -n
    return n


def _gen_natural_language(rng: random.Random, count: int) -> Iterator[str]:
    templates = [
        "{verb} the total number of {noun} if {name} has {a} and buys {b} more.",
        "{verb} how many {noun} remain after {a} of {b} are removed.",
        "What is {a} plus {b}?",
        "What is the difference between {a} and {b}?",
        "How many {noun} does {name} have after combining {a} and {b}?",
        "What percentage of {b} {noun} is {a} {noun}?",
        "{name} has {a} {noun}. {name2} has {b} {noun}. How many do they have together?",
        "{verb} the average of {a}, {b}, and {c}.",
        "A train travels {a} miles in {b} hours. What is its average speed?",
        "{verb} the perimeter of a rectangle with length {a} and width {b}.",
    ]
    for _ in range(count):
        t = rng.choice(templates)
        a, b, c = _rand_int(rng, 3, False), _rand_int(rng, 3, False), _rand_int(rng, 2, False)
        name, name2 = rng.sample(_NAMES, 2)
        yield t.format(
            verb=rng.choice(_VERBS), noun=rng.choice(_NOUNS), name=name, name2=name2, a=a, b=b, c=c
        )


def _gen_arithmetic(rng: random.Random, count: int) -> Iterator[str]:
    ops = ["+", "-", "*", "/"]
    for _ in range(count):
        kind = rng.random()
        if kind < 0.55:
            a, b = _rand_int(rng, 6), _rand_int(rng, 6, allow_negative=False) or 1
            yield f"{a} {rng.choice(ops)} {b}"
        elif kind < 0.7:
            base = rng.randint(2, 12)
            exp = rng.randint(2, 10)
            yield f"{base}^{exp}"
        elif kind < 0.85:
            yield f"sqrt({rng.randint(0, 999)})"
        else:
            yield rng.choice(
                ["one hundred twenty-three", "negative seven", "three quarters", "zero", "forty-two"]
            )


def _gen_algebra(rng: random.Random, count: int) -> Iterator[str]:
    templates = [
        "x + {a} = {b}",
        "{a}x - {b} = {c}",
        "y = {a}x + {b}",
        "{a}(x + {b})",
        "x^2 + {a}x + {b}",
        "{a}x + {b}y = {c}",
        "f(x) = x^2 + {a}",
        "solve for x: {a}x = {b}",
    ]
    for _ in range(count):
        t = rng.choice(templates)
        a, b, c = rng.randint(1, 99), rng.randint(1, 99), rng.randint(1, 99)
        yield t.format(a=a, b=b, c=c)


def _gen_percentages(rng: random.Random, count: int) -> Iterator[str]:
    for _ in range(count):
        kind = rng.random()
        p = round(rng.uniform(0, 100), rng.choice([0, 1, 2]))
        if kind < 0.4:
            yield f"{p}%"
        elif kind < 0.6:
            yield f"{p} percent"
        elif kind < 0.8:
            yield f"increase by {p}%"
        else:
            yield f"decrease by {p}%"


def _gen_ratios(rng: random.Random, count: int) -> Iterator[str]:
    for _ in range(count):
        a, b = rng.randint(1, 99), rng.randint(1, 99)
        kind = rng.random()
        if kind < 0.35:
            yield f"{a}:{b}"
        elif kind < 0.6:
            yield f"{a}/{b}"
        elif kind < 0.8:
            yield f"{a} to {b}"
        else:
            c, d = rng.randint(1, 99), rng.randint(1, 99)
            yield f"x/{a} = {c}/{d}"


def _gen_units(rng: random.Random, count: int) -> Iterator[str]:
    for _ in range(count):
        val = round(rng.uniform(0, 9999), rng.choice([0, 1, 2]))
        unit = rng.choice(_UNITS)
        sep = "" if rng.random() < 0.5 else " "
        yield f"{val}{sep}{unit}"


def _gen_financial(rng: random.Random, count: int) -> Iterator[str]:
    templates_amount = [
        "${amount}",
        "${amount:,.2f}",
    ]
    words = [
        "APR",
        "APY",
        "interest",
        "principal",
        "monthly payment",
        "compound interest",
        "discount",
        "tax",
        "tip",
        "profit",
        "loss",
    ]
    for _ in range(count):
        if rng.random() < 0.6:
            amount = rng.uniform(0, 50000)
            yield rng.choice(templates_amount).format(amount=amount)
        else:
            w = rng.choice(words)
            pct = round(rng.uniform(0, 30), 2)
            yield f"{w} of {pct}% on a principal of ${round(rng.uniform(100, 20000), 2):,.2f}"


def _gen_scientific(rng: random.Random, count: int) -> Iterator[str]:
    for _ in range(count):
        mantissa = round(rng.uniform(1, 9.999), rng.choice([1, 2, 5]))
        exp = rng.randint(-30, 30)
        kind = rng.random()
        if kind < 0.4:
            yield f"{mantissa}e{exp}"
        elif kind < 0.7:
            yield f"{mantissa}E{exp}"
        else:
            yield f"{mantissa} × 10^{exp}"


def _gen_explanations(rng: random.Random, count: int) -> Iterator[str]:
    for _ in range(count):
        t = rng.choice(_EXPLANATIONS)
        yield t.format(n=rng.randint(2, 99))


def _gen_tool_syntax(rng: random.Random, count: int) -> Iterator[str]:
    exprs = ["2+2", "3*4-1", "sqrt(16)", "12/4", "x+5=9", "100*0.15"]
    for _ in range(count):
        kind = rng.random()
        expr = rng.choice(exprs)
        if kind < 0.4:
            yield rng.choice(_TOOL_TOKENS)
        elif kind < 0.75:
            yield f'<tool_call>{{"expression":"{expr}"}}</tool_call>'
        else:
            yield f'<tool_result>{{"value":{rng.randint(-999, 999)}}}</tool_result>'


def _gen_errors(rng: random.Random, count: int) -> Iterator[str]:
    for _ in range(count):
        yield f"<error>{rng.choice(_ERRORS)}</error>" if rng.random() < 0.5 else rng.choice(_ERRORS)


def _gen_general_english(rng: random.Random, count: int) -> Iterator[str]:
    for _ in range(count):
        length = rng.randint(4, 12)
        words = [rng.choice(_GENERAL_WORDS) for _ in range(length)]
        sentence = " ".join(words)
        yield sentence[0].upper() + sentence[1:] + "."


_GENERATORS = {
    "natural_language_math_problems": _gen_natural_language,
    "arithmetic": _gen_arithmetic,
    "algebra": _gen_algebra,
    "percentages": _gen_percentages,
    "ratios_proportions": _gen_ratios,
    "units": _gen_units,
    "financial_math": _gen_financial,
    "scientific_notation": _gen_scientific,
    "explanations": _gen_explanations,
    "tool_syntax": _gen_tool_syntax,
    "errors": _gen_errors,
    "general_english": _gen_general_english,
}


@dataclass(frozen=True)
class CorpusLine:
    category: str
    text: str


def category_counts(total_lines: int = DEFAULT_TOTAL_LINES) -> dict[str, int]:
    return {cat: round(total_lines * prop) for cat, prop in CATEGORY_PROPORTIONS.items()}


def generate_corpus(seed: int = MASTER_SEED, total_lines: int = DEFAULT_TOTAL_LINES) -> Iterator[CorpusLine]:
    """Deterministically generate the full tokenizer-training corpus.

    Categories are generated and interleaved in a fixed, sorted order so the
    output is byte-identical across runs given the same (seed, total_lines).
    """
    counts = category_counts(total_lines)
    for category in sorted(_GENERATORS):
        rng = _rng_for(category, seed)
        generator = _GENERATORS[category]
        for text in generator(rng, counts[category]):
            yield CorpusLine(category=category, text=text)


def write_corpus(path, seed: int = MASTER_SEED, total_lines: int = DEFAULT_TOTAL_LINES) -> int:
    """Write one line of text per corpus line to ``path``. Returns line count."""
    n = 0
    with open(path, "w", encoding="utf-8") as handle:
        for line in generate_corpus(seed=seed, total_lines=total_lines):
            text = line.text.replace("\n", " ").strip()
            if not text:
                continue
            handle.write(text + "\n")
            n += 1
    return n
